# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valuesets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='valuesets.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fvaluesets.proto\"\xb6\x01\n\x10\x43oreValueSetItem\x12\x14\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\t\x12\x12\n\x05label\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x17\n\ndefinition\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x05 \x01(\tH\x03\x88\x01\x01\x42\x08\n\x06_labelB\x08\n\x06_valueB\r\n\x0b_definitionB\x0e\n\x0c_description\"K\n\x15VariationValueSetItem\x12\x14\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\t\x12\x12\n\x05label\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_label\"q\n\x0cValueSetItem\x12&\n\tcore_vset\x18\x01 \x01(\x0b\x32\x11.CoreValueSetItemH\x00\x12)\n\x07var_set\x18\x02 \x01(\x0b\x32\x16.VariationValueSetItemH\x00\x42\x0e\n\x0cValueSetItem\"4\n\x10ValueSetResponse\x12 \n\tvaluesets\x18\x01 \x03(\x0b\x32\r.ValueSetItem\"\x90\x01\n\x16ValueSetRequestOptions\x12@\n\tread_mask\x18\x01 \x01(\x0b\x32(.ValueSetRequestOptions.ValueSetReadMaskH\x00\x88\x01\x01\x1a&\n\x10ValueSetReadMask\x12\x12\n\nfield_name\x18\x01 \x03(\tB\x0c\n\n_read_mask\"\x94\x01\n\x0fValueSetRequest\x12\x19\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x12,\n\x06params\x18\x03 \x01(\x0b\x32\x17.ValueSetRequestOptionsH\x02\x88\x01\x01\x42\x0f\n\r_accession_idB\x08\n\x06_valueB\t\n\x07_params2Q\n\x0eValueSetGetter\x12?\n\x18GetValueSetByAccessionId\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponseb\x06proto3'
)




_COREVALUESETITEM = _descriptor.Descriptor(
  name='CoreValueSetItem',
  full_name='CoreValueSetItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accession_id', full_name='CoreValueSetItem.accession_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='CoreValueSetItem.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='CoreValueSetItem.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='definition', full_name='CoreValueSetItem.definition', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='CoreValueSetItem.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_label', full_name='CoreValueSetItem._label',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_value', full_name='CoreValueSetItem._value',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_definition', full_name='CoreValueSetItem._definition',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_description', full_name='CoreValueSetItem._description',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=20,
  serialized_end=202,
)


_VARIATIONVALUESETITEM = _descriptor.Descriptor(
  name='VariationValueSetItem',
  full_name='VariationValueSetItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accession_id', full_name='VariationValueSetItem.accession_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='VariationValueSetItem.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_label', full_name='VariationValueSetItem._label',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=204,
  serialized_end=279,
)


_VALUESETITEM = _descriptor.Descriptor(
  name='ValueSetItem',
  full_name='ValueSetItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='core_vset', full_name='ValueSetItem.core_vset', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='var_set', full_name='ValueSetItem.var_set', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ValueSetItem', full_name='ValueSetItem.ValueSetItem',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=281,
  serialized_end=394,
)


_VALUESETRESPONSE = _descriptor.Descriptor(
  name='ValueSetResponse',
  full_name='ValueSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valuesets', full_name='ValueSetResponse.valuesets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=448,
)


_VALUESETREQUESTOPTIONS_VALUESETREADMASK = _descriptor.Descriptor(
  name='ValueSetReadMask',
  full_name='ValueSetRequestOptions.ValueSetReadMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_name', full_name='ValueSetRequestOptions.ValueSetReadMask.field_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=543,
  serialized_end=581,
)

_VALUESETREQUESTOPTIONS = _descriptor.Descriptor(
  name='ValueSetRequestOptions',
  full_name='ValueSetRequestOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_mask', full_name='ValueSetRequestOptions.read_mask', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VALUESETREQUESTOPTIONS_VALUESETREADMASK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_read_mask', full_name='ValueSetRequestOptions._read_mask',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=451,
  serialized_end=595,
)


_VALUESETREQUEST = _descriptor.Descriptor(
  name='ValueSetRequest',
  full_name='ValueSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accession_id', full_name='ValueSetRequest.accession_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ValueSetRequest.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='ValueSetRequest.params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_accession_id', full_name='ValueSetRequest._accession_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_value', full_name='ValueSetRequest._value',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_params', full_name='ValueSetRequest._params',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=598,
  serialized_end=746,
)

_COREVALUESETITEM.oneofs_by_name['_label'].fields.append(
  _COREVALUESETITEM.fields_by_name['label'])
_COREVALUESETITEM.fields_by_name['label'].containing_oneof = _COREVALUESETITEM.oneofs_by_name['_label']
_COREVALUESETITEM.oneofs_by_name['_value'].fields.append(
  _COREVALUESETITEM.fields_by_name['value'])
_COREVALUESETITEM.fields_by_name['value'].containing_oneof = _COREVALUESETITEM.oneofs_by_name['_value']
_COREVALUESETITEM.oneofs_by_name['_definition'].fields.append(
  _COREVALUESETITEM.fields_by_name['definition'])
_COREVALUESETITEM.fields_by_name['definition'].containing_oneof = _COREVALUESETITEM.oneofs_by_name['_definition']
_COREVALUESETITEM.oneofs_by_name['_description'].fields.append(
  _COREVALUESETITEM.fields_by_name['description'])
_COREVALUESETITEM.fields_by_name['description'].containing_oneof = _COREVALUESETITEM.oneofs_by_name['_description']
_VARIATIONVALUESETITEM.oneofs_by_name['_label'].fields.append(
  _VARIATIONVALUESETITEM.fields_by_name['label'])
_VARIATIONVALUESETITEM.fields_by_name['label'].containing_oneof = _VARIATIONVALUESETITEM.oneofs_by_name['_label']
_VALUESETITEM.fields_by_name['core_vset'].message_type = _COREVALUESETITEM
_VALUESETITEM.fields_by_name['var_set'].message_type = _VARIATIONVALUESETITEM
_VALUESETITEM.oneofs_by_name['ValueSetItem'].fields.append(
  _VALUESETITEM.fields_by_name['core_vset'])
_VALUESETITEM.fields_by_name['core_vset'].containing_oneof = _VALUESETITEM.oneofs_by_name['ValueSetItem']
_VALUESETITEM.oneofs_by_name['ValueSetItem'].fields.append(
  _VALUESETITEM.fields_by_name['var_set'])
_VALUESETITEM.fields_by_name['var_set'].containing_oneof = _VALUESETITEM.oneofs_by_name['ValueSetItem']
_VALUESETRESPONSE.fields_by_name['valuesets'].message_type = _VALUESETITEM
_VALUESETREQUESTOPTIONS_VALUESETREADMASK.containing_type = _VALUESETREQUESTOPTIONS
_VALUESETREQUESTOPTIONS.fields_by_name['read_mask'].message_type = _VALUESETREQUESTOPTIONS_VALUESETREADMASK
_VALUESETREQUESTOPTIONS.oneofs_by_name['_read_mask'].fields.append(
  _VALUESETREQUESTOPTIONS.fields_by_name['read_mask'])
_VALUESETREQUESTOPTIONS.fields_by_name['read_mask'].containing_oneof = _VALUESETREQUESTOPTIONS.oneofs_by_name['_read_mask']
_VALUESETREQUEST.fields_by_name['params'].message_type = _VALUESETREQUESTOPTIONS
_VALUESETREQUEST.oneofs_by_name['_accession_id'].fields.append(
  _VALUESETREQUEST.fields_by_name['accession_id'])
_VALUESETREQUEST.fields_by_name['accession_id'].containing_oneof = _VALUESETREQUEST.oneofs_by_name['_accession_id']
_VALUESETREQUEST.oneofs_by_name['_value'].fields.append(
  _VALUESETREQUEST.fields_by_name['value'])
_VALUESETREQUEST.fields_by_name['value'].containing_oneof = _VALUESETREQUEST.oneofs_by_name['_value']
_VALUESETREQUEST.oneofs_by_name['_params'].fields.append(
  _VALUESETREQUEST.fields_by_name['params'])
_VALUESETREQUEST.fields_by_name['params'].containing_oneof = _VALUESETREQUEST.oneofs_by_name['_params']
DESCRIPTOR.message_types_by_name['CoreValueSetItem'] = _COREVALUESETITEM
DESCRIPTOR.message_types_by_name['VariationValueSetItem'] = _VARIATIONVALUESETITEM
DESCRIPTOR.message_types_by_name['ValueSetItem'] = _VALUESETITEM
DESCRIPTOR.message_types_by_name['ValueSetResponse'] = _VALUESETRESPONSE
DESCRIPTOR.message_types_by_name['ValueSetRequestOptions'] = _VALUESETREQUESTOPTIONS
DESCRIPTOR.message_types_by_name['ValueSetRequest'] = _VALUESETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CoreValueSetItem = _reflection.GeneratedProtocolMessageType('CoreValueSetItem', (_message.Message,), {
  'DESCRIPTOR' : _COREVALUESETITEM,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:CoreValueSetItem)
  })
_sym_db.RegisterMessage(CoreValueSetItem)

VariationValueSetItem = _reflection.GeneratedProtocolMessageType('VariationValueSetItem', (_message.Message,), {
  'DESCRIPTOR' : _VARIATIONVALUESETITEM,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:VariationValueSetItem)
  })
_sym_db.RegisterMessage(VariationValueSetItem)

ValueSetItem = _reflection.GeneratedProtocolMessageType('ValueSetItem', (_message.Message,), {
  'DESCRIPTOR' : _VALUESETITEM,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:ValueSetItem)
  })
_sym_db.RegisterMessage(ValueSetItem)

ValueSetResponse = _reflection.GeneratedProtocolMessageType('ValueSetResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALUESETRESPONSE,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:ValueSetResponse)
  })
_sym_db.RegisterMessage(ValueSetResponse)

ValueSetRequestOptions = _reflection.GeneratedProtocolMessageType('ValueSetRequestOptions', (_message.Message,), {

  'ValueSetReadMask' : _reflection.GeneratedProtocolMessageType('ValueSetReadMask', (_message.Message,), {
    'DESCRIPTOR' : _VALUESETREQUESTOPTIONS_VALUESETREADMASK,
    '__module__' : 'valuesets_pb2'
    # @@protoc_insertion_point(class_scope:ValueSetRequestOptions.ValueSetReadMask)
    })
  ,
  'DESCRIPTOR' : _VALUESETREQUESTOPTIONS,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:ValueSetRequestOptions)
  })
_sym_db.RegisterMessage(ValueSetRequestOptions)
_sym_db.RegisterMessage(ValueSetRequestOptions.ValueSetReadMask)

ValueSetRequest = _reflection.GeneratedProtocolMessageType('ValueSetRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALUESETREQUEST,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:ValueSetRequest)
  })
_sym_db.RegisterMessage(ValueSetRequest)



_VALUESETGETTER = _descriptor.ServiceDescriptor(
  name='ValueSetGetter',
  full_name='ValueSetGetter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=748,
  serialized_end=829,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetValueSetByAccessionId',
    full_name='ValueSetGetter.GetValueSetByAccessionId',
    index=0,
    containing_service=None,
    input_type=_VALUESETREQUEST,
    output_type=_VALUESETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VALUESETGETTER)

DESCRIPTOR.services_by_name['ValueSetGetter'] = _VALUESETGETTER

# @@protoc_insertion_point(module_scope)
