# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valuesets.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvaluesets.proto\"\xda\x01\n\x0cValueSetItem\x12\x14\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\t\x12\x12\n\x05label\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nis_current\x18\x04 \x01(\x08H\x02\x88\x01\x01\x12\x17\n\ndefinition\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x06 \x01(\tH\x04\x88\x01\x01\x42\x08\n\x06_labelB\x08\n\x06_valueB\r\n\x0b_is_currentB\r\n\x0b_definitionB\x0e\n\x0c_description\"4\n\x10ValueSetResponse\x12 \n\tvaluesets\x18\x01 \x03(\x0b\x32\r.ValueSetItem\"\x90\x01\n\x16ValueSetRequestOptions\x12@\n\tread_mask\x18\x01 \x01(\x0b\x32(.ValueSetRequestOptions.ValueSetReadMaskH\x00\x88\x01\x01\x1a&\n\x10ValueSetReadMask\x12\x12\n\nfield_name\x18\x01 \x03(\tB\x0c\n\n_read_mask\"\xbc\x01\n\x0fValueSetRequest\x12\x19\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nis_current\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12,\n\x06params\x18\x04 \x01(\x0b\x32\x17.ValueSetRequestOptionsH\x03\x88\x01\x01\x42\x0f\n\r_accession_idB\x08\n\x06_valueB\r\n\x0b_is_currentB\t\n\x07_params2\x84\x02\n\x08ValueSet\x12?\n\x18GetValueSetByAccessionId\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponse\x12<\n\x13GetValueSetsByValue\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponse0\x01\x12=\n\x14GetValueSetsByDomain\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponse0\x01\x12:\n\x11GetValueSetStream\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'valuesets_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALUESETITEM._serialized_start=20
  _VALUESETITEM._serialized_end=238
  _VALUESETRESPONSE._serialized_start=240
  _VALUESETRESPONSE._serialized_end=292
  _VALUESETREQUESTOPTIONS._serialized_start=295
  _VALUESETREQUESTOPTIONS._serialized_end=439
  _VALUESETREQUESTOPTIONS_VALUESETREADMASK._serialized_start=387
  _VALUESETREQUESTOPTIONS_VALUESETREADMASK._serialized_end=425
  _VALUESETREQUEST._serialized_start=442
  _VALUESETREQUEST._serialized_end=630
  _VALUESET._serialized_start=633
  _VALUESET._serialized_end=893
# @@protoc_insertion_point(module_scope)
