# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valuesets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='valuesets.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fvaluesets.proto\"\xda\x01\n\x0cValueSetItem\x12\x14\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\t\x12\x12\n\x05label\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nis_current\x18\x04 \x01(\x08H\x02\x88\x01\x01\x12\x17\n\ndefinition\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x06 \x01(\tH\x04\x88\x01\x01\x42\x08\n\x06_labelB\x08\n\x06_valueB\r\n\x0b_is_currentB\r\n\x0b_definitionB\x0e\n\x0c_description\"4\n\x10ValueSetResponse\x12 \n\tvaluesets\x18\x01 \x03(\x0b\x32\r.ValueSetItem\"\x90\x01\n\x16ValueSetRequestOptions\x12@\n\tread_mask\x18\x01 \x01(\x0b\x32(.ValueSetRequestOptions.ValueSetReadMaskH\x00\x88\x01\x01\x1a&\n\x10ValueSetReadMask\x12\x12\n\nfield_name\x18\x01 \x03(\tB\x0c\n\n_read_mask\"\xbc\x01\n\x0fValueSetRequest\x12\x19\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nis_current\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12,\n\x06params\x18\x04 \x01(\x0b\x32\x17.ValueSetRequestOptionsH\x03\x88\x01\x01\x42\x0f\n\r_accession_idB\x08\n\x06_valueB\r\n\x0b_is_currentB\t\n\x07_params2\x8a\x02\n\x0eValueSetGetter\x12?\n\x18GetValueSetByAccessionId\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponse\x12<\n\x13GetValueSetsByValue\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponse0\x01\x12=\n\x14GetValueSetsByDomain\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponse0\x01\x12:\n\x11GetValueSetStream\x12\x10.ValueSetRequest\x1a\x11.ValueSetResponse0\x01\x62\x06proto3'
)




_VALUESETITEM = _descriptor.Descriptor(
  name='ValueSetItem',
  full_name='ValueSetItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accession_id', full_name='ValueSetItem.accession_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='ValueSetItem.label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ValueSetItem.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_current', full_name='ValueSetItem.is_current', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='definition', full_name='ValueSetItem.definition', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='ValueSetItem.description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_label', full_name='ValueSetItem._label',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_value', full_name='ValueSetItem._value',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_current', full_name='ValueSetItem._is_current',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_definition', full_name='ValueSetItem._definition',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_description', full_name='ValueSetItem._description',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=20,
  serialized_end=238,
)


_VALUESETRESPONSE = _descriptor.Descriptor(
  name='ValueSetResponse',
  full_name='ValueSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valuesets', full_name='ValueSetResponse.valuesets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=292,
)


_VALUESETREQUESTOPTIONS_VALUESETREADMASK = _descriptor.Descriptor(
  name='ValueSetReadMask',
  full_name='ValueSetRequestOptions.ValueSetReadMask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_name', full_name='ValueSetRequestOptions.ValueSetReadMask.field_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=425,
)

_VALUESETREQUESTOPTIONS = _descriptor.Descriptor(
  name='ValueSetRequestOptions',
  full_name='ValueSetRequestOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='read_mask', full_name='ValueSetRequestOptions.read_mask', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_VALUESETREQUESTOPTIONS_VALUESETREADMASK, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_read_mask', full_name='ValueSetRequestOptions._read_mask',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=295,
  serialized_end=439,
)


_VALUESETREQUEST = _descriptor.Descriptor(
  name='ValueSetRequest',
  full_name='ValueSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accession_id', full_name='ValueSetRequest.accession_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ValueSetRequest.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_current', full_name='ValueSetRequest.is_current', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='ValueSetRequest.params', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_accession_id', full_name='ValueSetRequest._accession_id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_value', full_name='ValueSetRequest._value',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_is_current', full_name='ValueSetRequest._is_current',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_params', full_name='ValueSetRequest._params',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=442,
  serialized_end=630,
)

_VALUESETITEM.oneofs_by_name['_label'].fields.append(
  _VALUESETITEM.fields_by_name['label'])
_VALUESETITEM.fields_by_name['label'].containing_oneof = _VALUESETITEM.oneofs_by_name['_label']
_VALUESETITEM.oneofs_by_name['_value'].fields.append(
  _VALUESETITEM.fields_by_name['value'])
_VALUESETITEM.fields_by_name['value'].containing_oneof = _VALUESETITEM.oneofs_by_name['_value']
_VALUESETITEM.oneofs_by_name['_is_current'].fields.append(
  _VALUESETITEM.fields_by_name['is_current'])
_VALUESETITEM.fields_by_name['is_current'].containing_oneof = _VALUESETITEM.oneofs_by_name['_is_current']
_VALUESETITEM.oneofs_by_name['_definition'].fields.append(
  _VALUESETITEM.fields_by_name['definition'])
_VALUESETITEM.fields_by_name['definition'].containing_oneof = _VALUESETITEM.oneofs_by_name['_definition']
_VALUESETITEM.oneofs_by_name['_description'].fields.append(
  _VALUESETITEM.fields_by_name['description'])
_VALUESETITEM.fields_by_name['description'].containing_oneof = _VALUESETITEM.oneofs_by_name['_description']
_VALUESETRESPONSE.fields_by_name['valuesets'].message_type = _VALUESETITEM
_VALUESETREQUESTOPTIONS_VALUESETREADMASK.containing_type = _VALUESETREQUESTOPTIONS
_VALUESETREQUESTOPTIONS.fields_by_name['read_mask'].message_type = _VALUESETREQUESTOPTIONS_VALUESETREADMASK
_VALUESETREQUESTOPTIONS.oneofs_by_name['_read_mask'].fields.append(
  _VALUESETREQUESTOPTIONS.fields_by_name['read_mask'])
_VALUESETREQUESTOPTIONS.fields_by_name['read_mask'].containing_oneof = _VALUESETREQUESTOPTIONS.oneofs_by_name['_read_mask']
_VALUESETREQUEST.fields_by_name['params'].message_type = _VALUESETREQUESTOPTIONS
_VALUESETREQUEST.oneofs_by_name['_accession_id'].fields.append(
  _VALUESETREQUEST.fields_by_name['accession_id'])
_VALUESETREQUEST.fields_by_name['accession_id'].containing_oneof = _VALUESETREQUEST.oneofs_by_name['_accession_id']
_VALUESETREQUEST.oneofs_by_name['_value'].fields.append(
  _VALUESETREQUEST.fields_by_name['value'])
_VALUESETREQUEST.fields_by_name['value'].containing_oneof = _VALUESETREQUEST.oneofs_by_name['_value']
_VALUESETREQUEST.oneofs_by_name['_is_current'].fields.append(
  _VALUESETREQUEST.fields_by_name['is_current'])
_VALUESETREQUEST.fields_by_name['is_current'].containing_oneof = _VALUESETREQUEST.oneofs_by_name['_is_current']
_VALUESETREQUEST.oneofs_by_name['_params'].fields.append(
  _VALUESETREQUEST.fields_by_name['params'])
_VALUESETREQUEST.fields_by_name['params'].containing_oneof = _VALUESETREQUEST.oneofs_by_name['_params']
DESCRIPTOR.message_types_by_name['ValueSetItem'] = _VALUESETITEM
DESCRIPTOR.message_types_by_name['ValueSetResponse'] = _VALUESETRESPONSE
DESCRIPTOR.message_types_by_name['ValueSetRequestOptions'] = _VALUESETREQUESTOPTIONS
DESCRIPTOR.message_types_by_name['ValueSetRequest'] = _VALUESETREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValueSetItem = _reflection.GeneratedProtocolMessageType('ValueSetItem', (_message.Message,), {
  'DESCRIPTOR' : _VALUESETITEM,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:ValueSetItem)
  })
_sym_db.RegisterMessage(ValueSetItem)

ValueSetResponse = _reflection.GeneratedProtocolMessageType('ValueSetResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALUESETRESPONSE,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:ValueSetResponse)
  })
_sym_db.RegisterMessage(ValueSetResponse)

ValueSetRequestOptions = _reflection.GeneratedProtocolMessageType('ValueSetRequestOptions', (_message.Message,), {

  'ValueSetReadMask' : _reflection.GeneratedProtocolMessageType('ValueSetReadMask', (_message.Message,), {
    'DESCRIPTOR' : _VALUESETREQUESTOPTIONS_VALUESETREADMASK,
    '__module__' : 'valuesets_pb2'
    # @@protoc_insertion_point(class_scope:ValueSetRequestOptions.ValueSetReadMask)
    })
  ,
  'DESCRIPTOR' : _VALUESETREQUESTOPTIONS,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:ValueSetRequestOptions)
  })
_sym_db.RegisterMessage(ValueSetRequestOptions)
_sym_db.RegisterMessage(ValueSetRequestOptions.ValueSetReadMask)

ValueSetRequest = _reflection.GeneratedProtocolMessageType('ValueSetRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALUESETREQUEST,
  '__module__' : 'valuesets_pb2'
  # @@protoc_insertion_point(class_scope:ValueSetRequest)
  })
_sym_db.RegisterMessage(ValueSetRequest)



_VALUESETGETTER = _descriptor.ServiceDescriptor(
  name='ValueSetGetter',
  full_name='ValueSetGetter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=633,
  serialized_end=899,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetValueSetByAccessionId',
    full_name='ValueSetGetter.GetValueSetByAccessionId',
    index=0,
    containing_service=None,
    input_type=_VALUESETREQUEST,
    output_type=_VALUESETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetValueSetsByValue',
    full_name='ValueSetGetter.GetValueSetsByValue',
    index=1,
    containing_service=None,
    input_type=_VALUESETREQUEST,
    output_type=_VALUESETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetValueSetsByDomain',
    full_name='ValueSetGetter.GetValueSetsByDomain',
    index=2,
    containing_service=None,
    input_type=_VALUESETREQUEST,
    output_type=_VALUESETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetValueSetStream',
    full_name='ValueSetGetter.GetValueSetStream',
    index=3,
    containing_service=None,
    input_type=_VALUESETREQUEST,
    output_type=_VALUESETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VALUESETGETTER)

DESCRIPTOR.services_by_name['ValueSetGetter'] = _VALUESETGETTER

# @@protoc_insertion_point(module_scope)
