# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: valuesets.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvaluesets.proto\"\xda\x01\n\x0cValueSetItem\x12\x14\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\t\x12\x12\n\x05label\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x17\n\ndefinition\x18\x04 \x01(\tH\x02\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x05 \x01(\tH\x03\x88\x01\x01\x12\x17\n\nis_current\x18\x06 \x01(\x08H\x04\x88\x01\x01\x42\x08\n\x06_labelB\x08\n\x06_valueB\r\n\x0b_definitionB\x0e\n\x0c_descriptionB\r\n\x0b_is_current\"m\n\x0fValueSetRequest\x12\x19\n\x0c\x61\x63\x63\x65ssion_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0euse_noncurrent\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\x0f\n\r_accession_idB\x11\n\x0f_use_noncurrent2\xb7\x01\n\x08ValueSet\x12;\n\x18GetValueSetByAccessionId\x12\x10.ValueSetRequest\x1a\r.ValueSetItem\x12\x38\n\x13GetValueSetsByTopic\x12\x10.ValueSetRequest\x1a\r.ValueSetItem0\x01\x12\x34\n\x0fGetAllValueSets\x12\x10.ValueSetRequest\x1a\r.ValueSetItem0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'valuesets_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VALUESETITEM._serialized_start=20
  _VALUESETITEM._serialized_end=238
  _VALUESETREQUEST._serialized_start=240
  _VALUESETREQUEST._serialized_end=349
  _VALUESET._serialized_start=352
  _VALUESET._serialized_end=535
# @@protoc_insertion_point(module_scope)
